[env:due]
platform = atmelsam
board = due
framework = arduino
lib_deps =
    Wire
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    I2C
    arduino-libraries/SD @ ^1.2.4
monitor_speed = 115200
build_flags =
    -I${PROJECT_DIR}/lib/Config
    -I${PROJECT_DIR}/lib/Audio
    -I${PROJECT_DIR}/lib/Bluetooth