# 공통 설정
[common]
lib_deps =
    Wire
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    I2C
    arduino-libraries/SD @ ^1.2.4
monitor_speed = 115200
build_flags =
    -I${PROJECT_DIR}/lib/Config
    -I${PROJECT_DIR}/lib/Audio
    -I${PROJECT_DIR}/lib/Bluetoothz

# Arduino Due
[env:due]
platform = atmelsam
board = due
framework = arduino
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}

# Arduino/Genuino 101
[env:genuino101]
platform = intel_arc32
board = genuino101
framework = arduino
lib_deps = ${common.lib_deps}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}